apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRT2djaGNkdzc3QXIxS081N1NUUEdIREFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSaE16VXpNREF5TUMwMU1XUTJMVFF5WWpJdE9UVmtPUzB5TURRellqUXhZVEZsWVRNdwpIaGNOTWpFd05qQTNNRGN5T1RVd1doY05Nall3TmpBMk1EZ3lPVFV3V2pBdk1TMHdLd1lEVlFRREV5UmhNelV6Ck1EQXlNQzAxTVdRMkxUUXlZakl0T1RWa09TMHlNRFF6WWpReFlURmxZVE13Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURTYVpLUDBlbUlDcThWNytGTy9VN3VLSG16NVZ4Y0ZCT2ZpQ1VLeTZOWQp5dUxRRXc5NWIyYjl0QmlBSGJtY0VlVzBsL0JsK2hHdjBSaFRRb3FXbitoSTRGbTUrTGdzTGpwWThQa3lZNVNzClBFZU9rRFZYb3VkZUs2UVI3anprRGN4SCtQRFZ5Mmd1andjNHd0aHZZVlVpbkhyNlhzbWlMaC9GYXlXTDd4MDcKMlYvTGtNKzB5Sno0S3JidGdGZm9FS2hvWWswQ0lEMXJPbXJaOHdPTGxCVjR3VUZKdkI2ellCSFpMT1I4dnI4Mgo0ampUUmRSb0NORDNrVlRmdy9sTXZZaXFtd003SHUrOVpobmFjSklubkpPaWVMcWRFWGE3dG1XcjJSYmd3SHUxCmZhbHkvNE00aThjci8rbmVKbm11NFJTbXd2MGZLaFhWcHpTSE83SmxZQmFOQWdNQkFBR2pRakJBTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTc3hCelAvamEycTZTYQpiRkh0dUxGYm5YMjg3REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVTI1MmlidVdjV2hLYmtDK21SZWQ2N1pqClVxQjZCUExyV2lRNnllWXAzbGQySmlLVllTN0VUSUtJaWdrcEVBNytBMmhpY3RLRnFPVWV0eHRoRnY3UUNyeDgKeFVXcVhUZkxEY0ErVHM1S3pMc2F2VEViOE54WHVsdjQwSW9CVVMzT2J4WW14RmpmRDZrVHdIT2syOHNXM1F2eQpiNy8yWGprNmxPZlpDdjRBeHFmemZNYlJBR0tTQnRsSUNTQlNpa3NqUXFiYzdwTE9VeWZKSDB0cEpXQ0s5WFl0Ckg3dUMyZ0NZa2EvUk9xTTRURVh6UTNXOHprc3hibVRqUWEzL0xWNU1uSjNWd3hEVW8rMFRDVUM5enhyN2VpL2UKQkYyN1pNbXloYXR5Z2JYbGYrek5JZGVGMXVNb0toUzNvUXQ5bERIdURrS1VjNzZEa2s4ZnRNTFUxb1dtbVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://34.89.153.117
  name: gke_kiwigrid-196414_europe-west3-c_production-shared-1
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRY1lDZnUxT0lQTWVBbE84cXdlSjY2akFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlReFltSTVaR1JtWlMwellUQm1MVFE0WkdFdE9USmpaUzFsWmpZeU1qUXlZekV4TlRFdwpIaGNOTWpFd05URTRNVEl3TXpBNFdoY05Nall3TlRFM01UTXdNekE0V2pBdk1TMHdLd1lEVlFRREV5UXhZbUk1ClpHUm1aUzB6WVRCbUxUUTRaR0V0T1RKalpTMWxaall5TWpReVl6RXhOVEV3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN0cGVBU1dOeWhxbGdqK2o5N2pRdDVLUTFzaHVqeDdScE1xYzhydElpeQozb0tnNXJOcnRkQnRJZk9aNDhBdS9IYWhvRGRwZFlPWVR1RXlNUUFxa3pSWGdUS3c5SERXVjBLUDBBeG4xU1IrCno0NlVDV2c2SE5VcE1QaVBONStNaTdxKy9BQ3phQmlBUXI5MnZJYVR6V3ZtT1A4elZWRzJxM3h3OEROLzRiT0IKdHdWNldFUnlOdTI5SkpsOUwxSjcxVWVNamN6SG82VVN6RXhmakVmbGdqSDlMaXVVSjUyNFhvTDk5Z0k1c3VpNgptK01Gc0ZUR0h3RkxrUXBIaGpMMkU2NjZVUDJrek1SWUpSb3c3QUYvTHE5b1BZOExVZjBBeUw3cTBCRWJoajZKCkRUUVhNQlhJMWx2ZWk5THFqS0FIZWRGNVdkM3FucTlUVFIrdndLQnVmYitMQWdNQkFBR2pRakJBTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSN1BjVmZHNktnTHc2LwpqN2N1Y3dvWUhDaVJKakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQlJWK1RXYWFHSGxVV24ySUEwZE81MTByCktub1dNL2QvVDJKdWJkcmhwUHp1WkY0QnFzWWU0bWVVSisySE1PdTVKN01XOVg5TzVXNXZhb2RvWk12U0srMmYKZFcrZERGOW9IYUJxc1BJbWJLNE1IaHBiditvSWgvVlc3b3R1OURjY0ppM3g2STh0NTFrTUx3WnVRYWJMdlVpVApSb0tJMWhqWEgvalVrWkZRRkRlalhkTWF2RXlBelEwL3dYZkJzVUE2VVdMU2Z5Uk9VL0N3Nnk5OU1JNThLeG5zCndWMXl0RzFjY1RoZWNQU1FpcGVzd1hQRVoxTHFIUHY5ajY5SnNDaHNVVXpvaTR5cHVydjRqeEJoT1NYSS9FZjQKVGx4bHFVSjB1RHZubm55MzdyQWZWUWlSOWF4VldRbE9GYVZGeGlYNGpaK1FsQ3VkSTNjc3Jjd0ZDRDZpK3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://35.246.242.238
  name: gke_kiwigrid-qa-220513_europe-west3-c_qa-shared-1
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lSQU80aWRseThMcXJ6MVoyVk5GRmpnRkV3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1l6VmtOR0UyT1dJdE5HRTNOaTAwTWpOakxXRmhORGd0Wm1Jek1qUTRPRFExTjJFdwpNQjRYRFRJeE1EVXlNVEV4TWpreU5Wb1hEVEkyTURVeU1ERXlNamt5TlZvd0x6RXRNQ3NHQTFVRUF4TWtZelZrCk5HRTJPV0l0TkdFM05pMDBNak5qTFdGaE5EZ3RabUl6TWpRNE9EUTFOMkV3TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBN1EwS3pQQklPMXVVV0h5c0pQc2ZYZ0NTcjhyVzdKblFNM043R0hORwo0RGc4STZua3JHU0lBc2dnb0p5RThNQUp4REt4cUttY3FOZkFxNi9sUk5UMDV2cWFvZTM1QzhKS3czS1pVRmV2CklHK3NXN1dRZ2hxVkJzTWR0U28xclZJeU1rL0NuU1MzaCs1ZENjekJxdGp3TTdCaDRhRmVYT20rRzlYQVg4ckYKUkErcnc4ZDRKT0o0ZzJncjk4Kzc4eUpSL0pKQk1tdXVhV1ZhZ2RTQkFZWnpZM2kzSUxQcDViTTFoUUw1QlZKWgpNWDdSWUtPV21HTGxqUkg1Z3d1MExla0ZDYlRUd0dKcHBNamhSK3dxRjFuUHFIMVFpQWp3aW5EYjVTbWtmcGVVCkVIWDBjQ3dORU9ieUZjeG1SREtPMWN0YndsYzEvYTg2aTFWM05WcU1sQytLendJREFRQUJvMEl3UURBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpWOXRkNzdMVVRrSwpiVDIyUCtOU0pPNGdKQmt3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURhQ1BrbEhoQUk1UklDeFFqSHdsc1NUCmtIaFhxd09UeDZuUlB5Y3BvdUN1eDBwaUloR0U4aUlEK3kyd0t3N2lHN2hERERTMzFod2ZFcEQxaGhFbXlyNkIKWEVCSTMxSjN4ak1RV2tnVjVvMHl4NWI1UnlOUFRBL1ZPZ3Q4UHI0WFR3aE1OT3lyK3hwSmM4VHF6RDRobDJwUQplWm90Z0RHWHEzSWxEdTlnUk9IWDBHQkpzQXROZTh1aGlObm10SmhWTHNwczFKSWVkNzRjeGFMOWM2aFo0V1hlCjBXMXVabFFObmRmREUwVEZsc2lMVnd3TzNjRFVBY2pIczBybThEQUJkVEdIdndJU1h3cmJNRWZvNy91dXJlcE8Kc0ROM1lvZGZxMzg3dE9tS2Rxamx0NXFYSDVpUUxSQjBwQTkycWNGT2NWd2tpMEpHc0ExZ1hFSWVyb2p2ZUtrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://34.107.73.237
  name: gke_kiwigrid-staging-220513_europe-west3-c_staging-shared-1
contexts:
- context:
    cluster: gke_kiwigrid-196414_europe-west3-c_production-shared-1
    user: kg-prod
  name: kg-prod
- context:
    cluster: gke_kiwigrid-qa-220513_europe-west3-c_qa-shared-1
    user: kg-qa1
  name: kg-qa1
- context:
    cluster: gke_kiwigrid-staging-220513_europe-west3-c_staging-shared-1
    user: kg-stg
  name: kg-stg
current-context: kg-qa1
kind: Config
preferences: {}
users:
- name: kg-prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: kg-qa1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: kg-stg
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
